# Base OS is Centos
FROM centos:8

# Define build arguments to be executed and passed during the docker build
# While building the image we have to pass these build args, and the docker engine will take those args
# to create a docker image.. Passing args to the docker build process.

# Requirements file to do pip install
ARG REQ_PIP_FILE
# Final Dir name 
ARG FINAL_DIR_NAME
# Image built by ?
ARG BUILT_BY

RUN echo "Image is built by ${BUILT_BY}"

# All the commands below will be executed on the base os ..i.e. in this case centos

# Install Python3
RUN yum install -y python3

# Create a directory named final
RUN mkdir ${FINAL_DIR_NAME}

# Copy from the host machine to the final dir
COPY ./application ./${FINAL_DIR_NAME}

RUN pwd && ls

# Install all the required packages using python pip
RUN python3 -m pip install -r ${REQ_PIP_FILE}

# This CMD command will not get triggered during image build,while running the container it will run the python program
CMD python3 finally/app.py