FROM centos:8
RUN yum -y install python3
RUN mkdir final
COPY ./application ./final
RUN pip3 install -r final/requirements
RUN cat final/flask_app.py
# This CMD command will not get triggered during image build,while running the container it will run the python program
CMD python3 final/flask_app.py
 
