apiVersion: v1
kind: Service
metadata:
  name: python-flask-application-service
spec:
  selector:
    app: python-flask-application-pod
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-application
  labels:
    app: python-flask-application-pod
spec:
  selector:
    matchLabels:
      app: python-flask-application-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: python-flask-application-pod
    spec:
      containers:
      - name: python-flask-application-app
        image: docker.io/jupiter19/jupiter19:tag-arun-reg-exercise004
        imagePullPolicy: Always
        env:
        - name: CODER
          value: "Arun"
        - name: FLASKHOSTNAME
          value: "0.0.0.0"
        - name: FLASKPORT
          value: "5000"
        ports:
        - containerPort: 5000
        